elementary/music

src/LibraryWindow.vala
* Reduce variable scope where possible
* Code style
* Organize
* Remove extra white space
* Rename variables
=> LibraryWindow.vala: Code Style fixes

AUTHORS, core/Playlists/SmartPlaylist.vala, core/Playlists/SmartQuery.vala, src/DataBase.vala, src/Dialogs/SmartPlaylistEditor.vala, src/LocalBackend/LocalLibrary.vala, src/LocalBackend/LocalSmartPlaylist.vala
Now users can search through URI. So they can create playlist for particular directory.
For example if I want to play music from particular directory then it can be done by searching "uri:/path/to/directory" or if I want to create a playlist from directory /path/to/directory then I will follow this steps:
1. Search "uri:/path/to/directory"
2. Select all results
3. Click : Right-click Menu > Add to playlist
4. Name it.
=> URI Filter : Search and SmartPlaylist

src/Widgets/EqualizerPopover.vala
* Add 12px margin between switch and combobox
* hexpand the combo
=> EQ: Add margin between widgets and expand combo

core/Widgets/SettingsWidgets.vala, src/Dialogs/PreferencesWindow.vala
* Use Gobject-style construction
* Vala-style properties
* Fixed some whitespace
* Fixed margins around widgets
* Use native method to add buttons to dialog
=> Rewrite prefs dialog in GObjet-style

core/PluginManager.vala, plugins/Devices/iPod/iPodPlaylistHelper.vala
Updates fsf address in license headers
=> Update fsf address

src/Dialogs/MediaEditor.vala
this removes a function and 12 extraneous variables assigned when opening the metadata editor. ~~~but does touch the design somewhat.~~~
I for one welcome the muted gray, Grante.HeaderLabel was designed for bold headings on a Dialog.
=> Media editor cleanup

core/Settings.vala, schemas/org.pantheon.noise.gschema.xml
=> Remove unused album art gsettings key

src/Views/ContentView.vala, src/Views/GridView/GridView.vala, src/Views/ListView/ListView.vala, src/Views/Wrappers/ViewWrapper.vala, src/Widgets/StatusBar.vala
This information isn't particularly useful
=> Remove statusbar text

src/Views/GridView/PopupListView.vala
Allow the window to be resized, don't try to resize it
=> PopupListView.vala: Remove window resizing

src/Views/GridView/PopupListView.vala
Re-layout a bit so that this view makes sense in a portrait aspect ratio
=> Popup list view portrait

src/Widgets/AlbumListGrid.vala
Looks like it was just a typo, the signal was already disconnected by reset but never connected.
=> Update cover on change in AlbumListGrid

src/Views/ListView/Lists/MusicListView.vala
Use a switch/case statement and cache selected media while we're here for legibility
=> MusicListView.vala: allowing removing media from album list

src/Widgets/ViewSelector.vala
* Organized so that every time we touch modebutton is in the same place
* Remove unnecessary set size request
* Removed unnecessary halign and valign
* Removed unnecessary invisible widget. Set selection to -1 instead
* Minor code style tweaks, brackets, spacing, etc
=> ViewSelector.vala: Adjust modebutton properties

core/Settings.vala, src/Views/ListView/ListView.vala
Init GLib.Settings once instead of in each method
=> ListView.vala: Port saved_state_settings to GLib.Settings

src/Views/ListView/ListView.vala
* Don't set scroll policy because automatic is the default value
* Group hpane and vpane properties respectively
* Remove unnecessary CSS class
* Bracket all the things
=> ListView.vala: misc code style fixes

data/org.pantheon.noise.gschema.xml, src/LibraryWindow.vala
Music now saves and restores window position, fixes #184
=> Save / restore window position

core/Settings.vala, src/Views/ListView/ColumnBrowser/MusicColumnBrowser.vala
* Get rid of Granite.Settings for SavedState
* Convert to GLib.Settings
* Only create saved_state_settings once in this class
* Get rid of method only used once
=> MusicColumnBrowser.vala: Use GLib.Settings

core/Settings.vala, data/org.pantheon.noise.gschema.xml, src/LibraryWindow.vala
Be desktop agnostic. Don't try to be clever.
=> Remove checks for XDG Shell

src/Widgets/PresetList.vala
Changes tabs to spaces. No other changes
=> PresetList.vala: tabs to spaces

src/Objects/MediaKeyListener.vala
* Use brackets
* Space before `()`
* cuddle `catch`
* Use a switch/case instead of elseif/elseif/elseif
=> Mediakey code style

src/Dialogs/SmartPlaylistEditor.vala
got sick of chasing regressions in the fix-smartplaylist-editor branch. going to incrementally bring over the improvements and leave the regressions where they are.
=> made Noise.SmartPlaylistEditorQuery a private class called EditorQuery

.travis.yml
Music has tests, so make sure we run them
=> Run test target

core/Devices/Device.vala, core/Devices/DeviceManager.vala
* Remove unused `will_fit_without`
* Space before `()`
=> Device.vala: Remove unused code, code style

src/Views/ContentView.vala
We removed that statusbar earlier
=> Remove unused constant from ContentView

src/Widgets/TopDisplay.vala
PlayBackManager [already checks settings](https://github.com/elementary/music/blob/master/src/PlaybackManager.vala#L191) for this, so this is redundant
=> TopDisplay: Remove redunant settings check

src/DataBase.vala
=> Fixed Whitespace in Database.vala

src/PlaybackManager.vala
* Make things private that are only used in this class
* Remove unused things
=> PlayBackManager: Remove unused methods, make things private

src/PlaybackManager.vala
Alternative to #248, also fixes #242
=> Open unsupported files with their default application

CMakeLists.txt
Need to test if this breaks translations
=> Change gettext name to project name

meson.build
=> use RDNN for lib dir

README.md
new devs should set the correct prefix from the start.
=> fixed build instructions

meson.build, src/Views/AlbumsView.vala, src/Views/Wrappers/MusicViewWrapper.vala, src/Views/Wrappers/ViewWrapper.vala
=> Rename GridView to AlbumsView

src/Widgets/SourceListView.vala
* GObject-style
* Use switch instead of if if if
* Don't repeat things that happen in every condition
* Rename variables
* Space before ()
* Reduce variable scope
=> Source list view code style

src/Views/GridView.vala
Set methods to private that are only used here and remove an unused method
=> GridView.vala: reduce method scope

src/Widgets/StatusBar.vala
* Bump copyright header
* Remove `namespace`
* Remove unnecessary private class
* Get our own smart playlist editor as in #265
=> StatusBar.vala: simplify

meson.build, plugins/Devices/AudioPlayers/meson.build, plugins/Devices/CDRom/meson.build, plugins/Devices/iPod/meson.build, plugins/LastFM/meson.build
This probably shouldn't be merged until we figure out how to make plugins not crash Music. Otherwise it blocks all other development/testing/usage of the app
=> Install plugins again

src/GStreamer/GStreamerTagger.vala
=> fix parameter for ppa/juno version

src/Views/ListView/Lists/GenericList.vala, src/Views/ListView/Lists/MusicListView.vala, src/Widgets/AlbumListGrid.vala
Another change from #265 
Don't rely on a hint here, just set header visibility explicitly
=> Set header visibility explicitly

src/Dialogs/RemoveFilesDialog.vala, src/Views/ListView/Lists/MusicListView.vala
A change that was made in #265, while not really related.
=> Remove useless ViewWrapper.Hint

src/LocalBackend/LocalLibrary.vala
It was empty before. Needed by #265
=> Actually fill LocalLibrary.p_music

data/io.elementary.music.gschema.xml
Upstreams the settings from https://github.com/elementary/default-settings/pull/38
=> Move defaults from default-settings upstream

src/LibraryWindow.vala
Fixes ellipse when menu button is active
=> Valign menu button to fix visual bug

src/LibraryWindow.vala, src/Views/ListView/Lists/GenericList.vala, src/Views/ViewStack.vala, src/Widgets/SourceListView.vala
Makes the code a bit more simple.
=> SourceList: Use widgets directly instead of their IDs

src/Objects/HistoryPlaylist.vala, src/Objects/MPRIS.vala, src/Objects/MediaKeyListener.vala
* Replace `IOError` with GLib.Error
* Add `throws GLib.Error` to fix warnings
=> Fix warnings about using GLib.Error

src/Widgets/EqualizerPopover.vala
A small aesthetic improvement
Old
New
=> Fixing Switch

src/Views/ListView/ListView.vala, src/Views/Wrappers/ViewWrapper.vala
Fixes #147 and #186 
Needs #329 to be merged first
=> Don't go to list view when changing the queue

src/Application.vala, src/LibraryWindow.vala, src/Views/ListView/ColumnBrowser/MusicColumnBrowser.vala, src/Views/ListView/ListView.vala
Instead of creating multiple settings objects
=> Move saved state settings to Application class

meson.build, src/Views/ListView/Lists/MusicListView.vala, src/Widgets/ContractMenuItem.vala
=> Move ContractMenuItem class to its own file

meson.build, po/POTFILES, src/Views/ListView/Lists/GenericList.vala, src/Views/ListView/Lists/MusicListView.vala, src/Widgets/AlbumListGrid.vala, src/Widgets/MediaMenu.vala, src/Widgets/TopDisplay.vala
This is necessary for eventually using different types of widgets to represent Media such as in #350 
I get this is kind of a big diff. Some of these changes can probably be done in smaller steps if necessary. Let me know :)
=> Separate MediaMenu from MusicListView

src/PlaybackManager.vala
This is only used once as a get
=> PlaybackManager: Remove is_shuffled property

src/Views/ListView/Lists/CellDataFunctionHelper.vala, src/Views/ListView/Lists/MusicListView.vala
These are only used one time in MusicListView so put them there
=> Move one-liners from CellDataFunctionHlper to MusicListView

src/Views/AlbumsView.vala
=> AlbumsView: Use GObject-style

src/Views/ListView/ListView.vala
Replace a bunch of crazy add/remove widget stuff with a single Gtk.Paned
Replace all the settings get/set stuff with a simple bind/unbind
=> ListView.vala: use a single Gtk.Paned

README.md, core/Album.vala, core/Utils/Search.vala, docs/meson.build, meson.build, meson_options.txt, src/Views/ListView/Lists/GenericList.vala, src/Views/Wrappers/ViewWrapper.vala, src/Widgets/FastView/FastGridModel.vala, src/Widgets/FastView/FastListModel.vala
I think it mostly works, but when you try to build it chokes on some of the comments, not sure what to make of it, maybe I'm doing something wrong.
=> added documentation target and doc directory

src/Dialogs/NotImportedWindow.vala
=> NotImportedWindow.vala: use ngettext

core/Settings.vala, src/FileOperator.vala, src/LibraryWindow.vala
Move several non-core settings to GLib.Settings
=> Move more settings to GLib

data/io.elementary.music.gschema.xml, src/LibraryWindow.vala
* Fixed - Changed setting name to window-maximized and to be of type boolean.
=> Make window_state setting a boolean #365

src/LibraryWindow.vala
=> LibraryWindow: remove single-use build_main_widgets

src/Views/AlbumsView.vala, src/Widgets/AlbumListGrid.vala, src/Widgets/FastView/FastGrid.vala
=> Add support double-click to play in album view

core/Settings.vala, src/PlaybackManager.vala, src/Views/ListView/Lists/GenericList.vala, src/Views/ListView/Lists/MusicListView.vala
=> Fix queue problems

src/Dialogs/PreferencesWindow.vala, src/LocalBackend/LocalLibrary.vala
Resolves #453 and #295 by saving the music folder location that was changed through the API
=> Persists selected music library folder when changed through the GUI

src/Objects/MediaKeyListener.vala
=> MediaKeyListener: Update to new DBus location

src/LibraryWindow.vala
Fixes #499 
Move window.show location to consider headerbar size in set_default_size
=> Fix remembering last window size

src/PlaybackManager.vala, src/Views/ListView/Lists/MusicListView.vala, src/Views/Wrappers/ViewWrapper.vala, src/Widgets/MediaMenu.vala
=> Fix removing from queue

core/Utils/FileUtils.vala
This code appears unused all throughout the repository. Removing it still compiles cleanly.
=> Remove dead code

data/io.elementary.music.appdata.xml.in
Use two spaces
elementary LLC → elementary Inc
=> AppData: two space XML

src/DataBase.vala, src/FileOperator.vala, src/LibraryWindow.vala, src/PlaybackManager.vala
There are a few exceptions i haven't dealt with, but to ease the pr diff for reviewers, i'll handle those in some other pr's.
=> lint top level src files with vala-lint

src/Dialogs/NotImportedDialog.vala
* Reduce method scope
* Remove unused method
=> NotImportedDialog: misc cleanup

.travis.yml
=> Travis: Specify v10.17.0 for node_js

src/LibraryWindow.vala, src/PlaybackManager.vala
=> Enable playback buttons on startup if media is available

debian/control, debian/noise.install
Remove libdbus-glib, libdbusmenu* dependencies and add libhandy-1
=> Fix dependencies and wrap-and-sort the folder

src/LibraryWindow.vala, src/Views/ListView/Lists/CellDataFunctionHelper.vala, src/Widgets/FastView/FastGrid.vala, src/Widgets/PresetList.vala
* LibraryWindow.vala Unsafe casts
* CellDataFunctionHelper.vala Unsafe casts
* FastGrid.vala Delegate functions as properties
* PresetList.vala Unsafe casts
=> Fix some terminal warnings

src/LibraryWindow.vala, src/Widgets/StatusBar.vala
While we're here, code style and make sure primary action has a label
=> StatusBar: use flat style

data/application.css
=> Styles: Define accent color for elementary OS 6

.github/workflows/main.yml, io.elementary.music.yml
The manifest don't include any plugin, so no device access. Also, no gst-plugins-ugly, so codecs incompatibility can occur.
Fixes #612.
=> Add flatpak manifest

src/Dialogs/SmartPlaylistEditor.vala
=> SmartPlaylistEditor: Use add_button

src/DataBase.vala, src/Dialogs/SmartPlaylistEditor.vala, src/LocalBackend/LocalSmartPlaylist.vala
Fixes #197 
Also fixes another issue noticed while fixing the linked one - the view now updates when saving after changing the any/all combobox setting.
=> Fix invalid datatype when saving smart playlist

io.elementary.music.yml
* Update Dependencies
* Remove Unnecessaries DBus addresses
* Use Granite '6.0.0' tag
=> Update Flatpak Manifest

data/music.desktop.in, src/PlaybackManager.vala
Nice bit of feedback when we queue tracks from another app
Give the queue notifications a unique ID so that they replace each other
=> PlaybackManager: Notify when tracks are queued

data/PlaybackIndicator.css, data/music.gresource.xml, data/playback-indicator/paused.svg, data/playback-indicator/playing-00.svg, data/playback-indicator/playing-01.svg, data/playback-indicator/playing-02.svg, data/playback-indicator/playing-03.svg, data/playback-indicator/playing-04.svg, data/playback-indicator/playing-05.svg, data/playback-indicator/playing-06.svg, data/playback-indicator/playing-07.svg, data/playback-indicator/playing-08.svg, data/playback-indicator/playing-09.svg, data/playback-indicator/playing-10.svg, data/playback-indicator/playing-11.svg, data/playback-indicator/playing-12.svg, data/playback-indicator/playing-13.svg, data/playback-indicator/playing-14.svg, data/playback-indicator/playing-15.svg, data/playback-indicator/playing-16.svg, data/playback-indicator/playing-17.svg, src/Application.vala, src/MainWindow.vala, src/Widgets/SeekBar.vala, src/Widgets/TrackRow.vala, src/meson.build
* Create TrackRow
* Add an animated playback indicator
* Set accent color to orange
=> TrackRow: add animated playback indicator

data/AlbumImage.css, data/Application.css, data/music.gresource.xml, io.elementary.music.yml, meson.build, src/Application.vala, src/MainWindow.vala, src/PlaybackManager.vala, src/Views/NowPlayingView.vala, src/Widgets/AlbumImage.vala, src/Widgets/SeekBar.vala, src/Widgets/TrackRow.vala
=> Port to Gtk4

src/Application.vala, src/PlaybackManager.vala, src/Views/NowPlayingView.vala
=> Application: create action_next

src/MainWindow.vala
=> MainWindow: use Granite.Placeholder

src/Application.vala, src/PlaybackManager.vala
=> PlaybackManager: more accurately track play state

src/PlaybackManager.vala
Preperation step to playing arbitrary audio objects
=> PlaybackManager: DRY changes to current_audio

src/MainWindow.vala, src/PlaybackManager.vala
=> MainWindow: activate row to play

src/MainWindow.vala
=> Queue: Accept drop

src/Application.vala, src/MainWindow.vala, src/PlaybackManager.vala, src/Widgets/TrackRow.vala
Fixes #687 
Drafting because there's no "un-shuffle"
=> PlaybackManager: shuffle

.github/workflows/ci.yml
use the right docker container for faster builds
=> CI: Use daily docker

.github/workflows/merge.yml, .github/workflows/release.yml
Adds Music daily builds to the AppCenter remote and stable build on release tag
=> Create Flatpak deploy actions

debian/control, debian/install, debian/postinst, debian/prerm
Based on Screenshot: https://github.com/elementary/screenshot/tree/deb-packaging/debian
=> Install Music Flatpak

src/MainWindow.vala, src/PlaybackManager.vala
Aims to help with https://github.com/elementary/music/pull/711
@vjr I tried it :)
=> Use signal to notify when to show error toast

data/music.metainfo.xml.in, meson.build
Also includes bump to latest flatpak platform
=> Release 7.1.0

src/Application.vala
=> Add quit keyboard shortcut

src/PlaybackManager.vala
This adds code clarity and makes sure we have dedicated handlers for whatever comes next.
=> Move lambdas into handlers

README.md
- Fix missing libadwaita-1
- Explicit version limitation of granite-7
=> README: Update dependencies list

data/music.metainfo.xml.in, meson.build
=> Release 8.1.0
