elementary/music

AUTHORS
src/LibraryWindow.vala
src/LocalBackend/LocalLibrary.vala

Re-scan the local music folder at startup for any changes made while the application wasn't running.
related to https://bugs.launchpad.net/noise/+bug/1073871

Detect library changes at startup

---

src/LocalBackend/LocalLibrary.vala

The comparison is carried out on line 544 and the variable never used, as it is only carried out once there is no reason to use the variable here.

Remove unused local variable rating_search

---

core/Playlists/Playlist.vala
src/LocalBackend/LocalSmartPlaylist.vala
src/LocalBackend/LocalStaticPlaylist.vala

Constructing the name property  (when it just gets set to null), before the connection is assigned, results in critical terminal warning.

Remove unnecessary construct Playlist name property.

---

core/Utils/String.vala
src/Widgets/FastView/FastListModel.vala

Fix code so "use of possibly unassigned" compilation errors are not produced.
The third commit also corrects a logical error in the function where the assignment was the wrong way around.

Fix possibly unassigned

---

src/Dialogs/PreferencesWindow.vala

- switched SettingsHeaders to use Granite.HeaderLabel
- deleted private class SettingsHeader reimplementing Granite.HeaderLabel
- removed an unused variable from the static notebook version of preferences

Use Granite HeaderLabel in prefs window

---

src/Views/GridView/GridView.vala

Rely on `Gtk.WindowPosition.CENTER_ON_PARENT` and don't try to manually position the window

GridView.vala: Don't manually position popup

---

plugins/MPRIS/SoundMenuIntegration.vala
src/Noise.vala

GLib.Application already provides get_application_id which serves the same purpose.

Remove App.get_id

---

plugins/MPRIS/MPRIS.vala
plugins/MPRIS/SoundMenuIntegration.vala
src/Dialogs/NotImportedWindow.vala
src/Dialogs/RemoveFilesDialog.vala
src/FileOperator.vala
src/LibraryWindow.vala
src/Noise.vala

Removes get_name and get_desktop_file_name from Noise.App and instead directly uses fields.

Use Granite.Application fields

---

src/Noise.vala

Granite handles this so the code has no effect.

Leave debug handling to Granite

---

src/Views/ListView/Lists/MusicListView.vala

redid it, it's actually even better.
- renamed variables in elementary style
- renamed methods in elementary style (except a public one)
- removed two separator declarations
- grouped property changes with the associated object
- removed build_ui() method and placed it's arguments in constructor
- fixed the two submenus in the same ways.
- fixed inconsistent spacing
- changed `update_sensitivities()` to use a switch/case block

Cleaned MusicListView

---

src/Widgets/SimpleOptionChooser.vala
src/Widgets/StatusBar.vala

* Tabs to spaces
* Private variables are explicitly `private`
* Code style
* Remove `menu_only_mode` as this is unused and Gtk.MenuButton exists for this purpose
* Fix JS-style method names
* `append_item` accepts a string `icon_name` rather than a Gtk.Image

SimpleOptionChooser.vala: code style and simplify

---

data/application.css
src/Widgets/SimpleOptionChooser.vala
src/Widgets/StatusBar.vala
src/Widgets/TopDisplay.vala

Fixes #118 
Fixes #117 
* Move shuffle and repeat choosers into the top display
* Move the eventbox only around the time label itself so we don't block right clicks on the chooser buttons. The label is hexpanded so the hitbox is still pretty big.
* Stop double click event from propogating

Move shuffle and repeat choosers into top display

---

core/Player.vala
data/org.pantheon.noise.gschema.xml
src/Widgets/SimpleOptionChooser.vala
src/Widgets/TopDisplay.vala

We only have three states now: off, song or all
Drop the context menu on both the repeat chooser and the shuffle mode selector
Fixes #71

Simplify repeat modes

---

src/Dialogs/SyncWarningDialog.vala
src/Views/DeviceSummaryWidget.vala

Subclass Granite.MessageDialog instead of Gtk.Dialog to save ourselves some work and get proper styling and alignment.
While we're here:
* change the icon from error (no error has actually occurred) to warning
* change the cancel action label to "Cancel"
* change the import action label to "Import"
* Add destructive and suggested action style classes
* Buttons in HIG order (Alternate, Cancel, Affirmative)
**OLD**
**NEW**

SyncWarningDialog.vala: subclass Granite.MessageDialog

---

src/Views/ListView/ColumnBrowser/BrowserColumnModel.vala

- removed `using Gtk;`
- associated Gtk classes with the Gtk namespace
- now readers should know where SortType and Tree are defined.

clarified namespaces

---

src/Widgets/EqualizerPopover.vala

* Replace `set_size_request ()` with `height_request`
* Remove some unnecessary `expand`s
* Use a Gtk.SizeGroup instead of witchcraft
* Remove some methods that only contained a single line
* Brackets on `if` and `for` statements
* Lines touched use spaces instead of tabs

EqualizerPopover.vala: misc cleanup

---

src/Dialogs/SmartPlaylistEditor.vala

- tidied up interface code
- deleted some unused variables
- ported to Granite.Headerlabel
- fixed a bug where saving a smart playlist would duplicate its contents

Clean up SmartPlaylistEditor.vala

---

core/Album.vala
core/Utils/Icon.vala
src/Views/GridView.vala

This fixes several warnings in the Terminal about failing to lookup icons
Album.vala:
* No additional icon lookup flags
Icon.vala:
* Don't try to append an icon directory since we use gresource now instead
* Whitespace
GridView.vala:
* Don't try to load a non-existent fallback pixbuf since we draw that in Gtk.CSS now

Fix icon warnings

---

core/Settings.vala
src/LibraryWindow.vala

Port the saved state settings in LibraryWindow to GLib.Settings instead of Granite Settings
* Remove now unused properties and enum from Settings.vala
* Decrease the scope of `window_height` and `window_width` to `configure_event`
* Increase the scope of `saved_state_settings` instead of recreating it in several methods
* Respect window manager defaults for placing windows without saved coords (For Gala this is still center, so no change)
* Bind `sidebar-width` instead of get/set

LibraryWindow.vala: port saved_state to GLib.Settings

---

src/LibraryWindow.vala
src/Widgets/ViewSelector.vala

Removed unused set visible because nothing was calling it
Remove get visible because it will always return `true`

ViewSelector.vala: Remove unused get/set visible

---

src/LibraryWindow.vala

If it's not > 5, it certainly won't be > 30

LibraryWindow.vala: stop an unnecessary played check

---

src/LibraryWindow.vala
src/Widgets/StatusBar.vala

We already run this check (`have_media`) in LibraryWindow.vala in order to set the source list category visibility. Instead of running the same check twice, just use the cached result of the first check and make statusbar dumber

Statusbar menubutton sensitive

---

core/Devices/Device.vala
src/LibraryWindow.vala
src/Views/DeviceView.vala

* GObject style
* `d` -> `device
* Reduce variable scope
* Remove unneeded cast to Gtk.Container in infobar
* "OK" -> "Close"
* Connect signals at the bottom
* Properties instead of get/set
* Organize
* Remove unused `set_as_current_view`
* Don't get device custom view twice

DeviceView.vala: misc cleanup

---

src/Widgets/ViewSelector.vala

* Brackets
* No need for `this`
* property `selected` instead of `set_active` method

ViewSelector.vala: minor code style cleanups

---

src/Widgets/FastView/TileView/TileRenderer.vala

This fixes an error `conversion to non-scalar type requested`

TileRenderer.vala: Fix compile error with Gtk.Border

---

debian/noise.install

This should fix a packaging build failure. We no longer install anything to `/usr/share/noise` since all assets are now bundled into a gresource

No longer reference usr/share

---

src/LibraryWindow.vala

Several methods were marked as public but only used in this class
`media_not_found` was never used at all

LibraryWindow.vala: Make public things private

---

core/Utils/TimeUtils.vala

* Remove a bunch of unused time utils code
* Use Granite.DateTime.seconds_to_time
* `SEC_INV` is only used here, so make it private

TimeUtils.vala: Remove dead code

---

core/Album.vala

* Remove commented code
* Sort public properties together
* Make `n_discs` private since it's only used here
* Combine `n_media` into `is_empty` since it's only used there
* Use `Object ()`

Album.vala: Remove dead code; simplify

---

src/Dialogs/SmartPlaylistEditor.vala

this minimal commit brings the remove button back, but doesn't perform any fancy styling or have any refactoring.

Show remove button

---

src/LibraryWindow.vala

doesn't fix #242 but it's a useless variable that's initialized false, set to false and never passed or tested.

LibraryWindow.vala Remove Unused Variable tested_for_video

---

CMakeLists.txt

Looks like the upstream issue linked here has been marked `RESOLVED FIXED`

Remove experimental build flag

---

src/Dialogs/FileNotFoundDialog.vala
src/Dialogs/SmartPlaylistEditor.vala
src/LibraryWindow.vala
src/Views/DeviceSummaryWidget.vala
src/Views/ListView/Lists/GenericList.vala
src/Views/ListView/Lists/MusicListView.vala
src/Widgets/PresetList.vala

* `margin_left` and `margin_right` have been replaced by `margin_start` and `margin_end`
* `set_rules_hint` isn't a thing anymore. You can't have alternating colored rows in treeview :(
* `follow_state` isn't a thing anymore because according to docs cell renderers always follow state
* `Gtk.Combobox.set_title` isn't a thing anymore because this was related to "tear off mode" whatever that is

Misc deprecation fixes

---

plugins/Devices/CDRom/CDRomDevice.vala
plugins/LastFM/LastFM.vala
src/CMakeLists.txt
src/LibraryWindow.vala
src/Views/ListView/Lists/GenericList.vala
src/Views/ViewContainer.vala
src/Views/ViewStack.vala
src/Views/Wrappers/ViewWrapper.vala

* Rename as ViewStack so we know what widget this subclasses
* Use `visible_child` instead of a `get_current_view ()` method
* Use `get_child_by_name ()` instead of `get_view ()` method
* Use `visible_child` and `visible_child_name` instead of `set_view` methods
* Listen to `visible_child` and `update_visible` if it changes and isn't null.
* Remove the null check from `update_visible` since we check that in the notify.connect
* Removed unused methods

Simplify ViewContainer as ViewStack

---

src/LibraryWindow.vala
src/PlaybackManager.vala
src/Views/Wrappers/MusicViewWrapper.vala

This branch ports the play/pause, next, and previous functions to GLib.Action. The reason I want to use GLib.Action here is because it allows us to reduce the amount of functions that are touching the UI. This makes it easier for us to move the whole headerbar into its own class in the future, which I think would be nice to break up this huge LibraryWindow class a little.
Since we don't have to touch the actual UI anymore when setting the playback action state, we can actually set this directly from the playback manager instead of having to listen for a signal in LibraryWindow.

Port playback controls to GLib.Action

---

src/Dialogs/SmartPlaylistEditor.vala
src/LibraryWindow.vala

Dialog property changes from #265 
We don't need to set the type hint to Dialog here since this is a Gtk.Dialog subclass

SmartPlaylistEditor.vala: set own properties

---

po/pl.po
src/Dialogs/SmartPlaylistEditor.vala

* Rename `sp` to `smart_playlist`
* Use GObject-style construction
* bump copyright
* merge unnecessary public `load_smart_playlist` with construct
* Only check if `smart_playlist` is null once in construct and remove `is_new`
* Remove unnecessary cast to Gtk.Container
* Reduce the scope of `main_grid`
* Use properties in code I touched

 SmartPlaylistEditor.vala: Use GObject style

---

plugins/Devices/CDRom/CDRomDeviceManager.vala
plugins/Devices/CDRom/CDView.vala

Some of the CD plugin cleanups from #265 plus a few of my own
* Bump copyright
* Spaces before ()
* Cuddle else
* Properties instead of set methods
* Organize
* `halign` and `valign` instead of `set_alignment`
* `author` and `title` to `author_label` and `title_label`

CD plugin code style cleanups

---

plugins/Devices/CDRom/CDView.vala

Seems like these are never used

CDView.vala: remove unused methods

---

plugins/Devices/AudioPlayers/meson.build
plugins/Devices/CDRom/meson.build
plugins/Devices/iPod/meson.build
plugins/LastFM/meson.build

Install is already set to `true` so no need to install the plugin again

Only install plugins once

---

src/Views/ListView/Lists/MusicListView.vala
src/Widgets/AlbumListGrid.vala

A change from #265 
Explicitly set if a view can be scrolled to the current playing song instead of relying on hints

Explicitly set can scroll to current

---

src/Views/ListView/Lists/MusicListView.vala

Don't special case the album sidebar here since we want that separator above the "Remove" item here

Show a separator above remove menuitem in album sidebar

---

src/Views/ListView/ListView.vala

It was always showing when playing a new media, because for some reason `table` was empty…

Fix a bug with alert view

---

src/Views/ListView/ListView.vala

There's another case where results are <1 and that's when the library is empty. Make sure that there are both no results and we're actually searching so that the welcome view shows on first run instead of the no results view

Only show alertview when search is non-null

---

src/LibraryWindow.vala
src/Widgets/SourceListView.vala

This doesn't change the functionality at all, but removes a reliance on `source_list_view.selected` when it comes to choosing which item to use when the "Rename" context menu item is used.
This fixes the right click rename functionality if https://github.com/elementary/granite/pull/190 is merged.

Don't rely on selected item in SourceList for rename

---

src/LibraryWindow.vala

This signal is never connected to and the variable is never changed from its default value of `false`

LibraryWindow: Remove unused signal and variable

---

core/Settings.vala

This fixes a bug that causes some state to be lost when privacy mode is inactive, and saves it when privacy mode is active.
Specifically this is used for remembering the last search, last track, etc

Fix inverted privacy mode settings

---

src/LibraryWindow.vala
src/Views/ViewStack.vala
src/Views/Wrappers/ViewWrapper.vala
src/Widgets/ViewSelector.vala

Instead of checking if the view selector is sensitive before performing actions, set the actions as disabled/enabled when we change the sensitivity of the selector.
Also use the `sensitive` property instead of `set_sensitive` to fix the selector not being unselected while insensitive

ViewSelector: Set view actions to disabled when insensitive

---

src/Widgets/MediaMenu.vala

There are some unaccounted for viewwrapper.Hint types. Assume that the default hint is read only

MediaMenu: default to read only actions

---

src/Views/ListView/Lists/GenericList.vala
src/Views/ListView/Lists/MusicListView.vala

There's a lot of things in GenericList that are only used by MusicListView. Moved those things there so we're not over-abstracting.
While we're here:
* Remove some commented lines
* `media_updated` never uses the variable it accepts and only calls one other method, so just call that directly from the one place it's used
* Make things private that are never used outside this class

Move things from GenericList to MusicListView

---

src/Views/AlbumsView.vala

Fixes #381 
It looks like this was used to close the album dialog back when. Now that we have it as a sidebar we don't need/want to close it every time we focus some other widget

AlbumsView: remove button press mask

---

data/application.css

Hotfix for a style regression.
Ideally we make these styles jive with all our apps, but for now this fixes the broken looking style

Overwrite system iconview css

---

core/Settings.vala
src/Widgets/EqualizerPopover.vala

Use GLib.Settings in EqualizerPopover where convenient.
Several of these settings are still touched in PlayBackManager so they can't be removed until that gets resolved. This is the same reason why I didn't touch the `get_presets ()` method.
Took the opportunity to change a few things to a settings bind

EqualizerPopover: use GLib.Settings

---

src/LibraryWindow.vala
src/LocalBackend/LocalLibrary.vala
src/PlaybackManager.vala
src/Views/ListView/Lists/GenericList.vala
src/Widgets/MediaMenu.vala

Fixes #347
It's not pretty, but it doesn't try to divide by 0.
Reverts to before [the queue mechanism was rewritten](https://github.com/elementary/music/pull/65), but trying to keep cleanups and such.

PlaybackManager: revert queue mechanism

---

src/Widgets/MediaMenu.vala

Apparently, someone forgot a break statement on end of the switch

Fix warning: Can't set a parent on widget which has a parent

---

src/LocalBackend/LocalLibrary.vala
src/LocalBackend/LocalMedia.vala

Fixes error when constructor fails propagating null object all over, therefore generating a lot of critical warnings and that might be a cause of some Noise's crashes
Output **before** fix
Total output lines(w/o empty lines): **9980 lines**
First 30 lines collapsing repeated errors
```
(io.elementary.music:24991): GLib-GObject-CRITICAL **: 21:24:22.334: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
(io.elementary.music:24991): GLib-GObject-CRITICAL **: 21:24:22.401: g_value_get_string: assertion 'G_VALUE_HOLDS_STRING (value)' failed
(io.elementary.music:24991): GLib-GObject-CRITICAL **: 21:24:22.619: Read-only property 'read-only-view' on class 'GeeReadOnlyBidirSortedSet' has type 'GeeSortedSet' which is not equal to or more restrictive than the type …
```

Handle error when a LocalMedia constructor fail

---

src/Dialogs/MediaEditor.vala

* All entries activate default
* Reduce var scope
* Connect to dialog response instead of individual buttons
* Remove grid properties that we don't need (orientation is horizontal by default. Image buttons are always the same width)

MediaEditor: Entries activate default and cleanups

---

data/application.css

Switches the accent color to orange, which gives it a nice subtle brand effect imho. Affects overshoot scroll feedback, selected tracks, loading bars, switches, etc.

Add orange accent color

---

plugins/Devices/CDRom/CDRomDevice.vala
plugins/Devices/CDRom/CDViewWrapper.vala
src/Dialogs/MediaEditor.vala

Disc:
"In most varieties of English, disk is the correct spelling for magnetic media (hence hard disk or disk drive), whereas the variant disc is usually preferred with optical media (hence compact disc or disc film)."
https://en.wiktionary.org/wiki/disk
Other errors spotted by @Sporiff :)

Spelling: Occurred, Could not load audio CD

---

src/Views/AlbumsView.vala

Fixes #231 
Albums appear in a different order every run, due to not suitable compare function in the TreeSet.

Make albums order fixed every run.

---

core/Resources.vala

Fixes #455 but without loading the metadata (this belong to GStreamer not Music)

Add s3m content type to media content types list.

---

src/Widgets/FastView/TileView/TileRenderer.vala

Fixes #395 
Adds support for loading album art on **HiDPI** monitors with the correct resolution.
Bei Monitoren mit hohen HiDPI Werten werden die Albumcover mit der falschen Auflösung geladen. Dieser Fix berücksichtigt den Skalierungsfaktor.

Fix: Blurred album images at high resolutions

---

src/Dialogs/PreferencesWindow.vala

If we use get_uri whitespace will be translated to %20 and the folder will not be found.

Fix music folder choosing

---

src/Application.vala

Pretty sure we don't need this since we're a Gtk.Application subclass

Application: Remove duplicate l10n support

---

plugins/Devices/AudioPlayers/AudioPlayerDeviceManager.vala

I'm not 100% sure of the ramifications of this, but I presume Android and/or USB audio players were not being detected correctly here.

AudioPlayerDeviceManager: Use actual OR operator

---

data/io.elementary.music.appdata.xml.in
src/Widgets/EqualizerPopover.vala

If you had equalizer turned off and selected anything except "Automatic", level sliders were still enabled.

Properly disable equalizer levels

---

src/Dialogs/PreferencesWindow.vala

Fixes #620 
* Not sure what this width and height request business was since we don't allow resizing. Let the widgets determine the window size
* Remove unused public property
* `deletable` and `window_position` are already set for Granite.Dialog
* Fix wonky margins

PreferencesWindow: Cleanup and fix layout

---

src/Dialogs/FileNotFoundDialog.vala

I guess this sentence should end with a period, not a question mark.

FileNotFoundDialog: Fix a typo

---

data/io.elementary.music.appdata.xml.in

This is needed for appstream-generator to find the associated desktop file.
See also:
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
- https://github.com/ximion/appstream-generator/issues/88

Add launchable tag to appdata

---

data/io.elementary.music.desktop.in

Just a tiny proposal, but I think we may want to remove the word "CD" from search words since Music no longer supports CDs: #577

desktop: No longer mention CD

---

src/MainWindow.vala

Maybe could use better copy? or at least file manager agnostic copy? Music files could theoretically be opened from other apps too I imagine

Listbox placeholder

---

src/Application.vala

Stops from spawning a new window every time we add a file to the queue

Application: only activate on open if playbackmanager is null

---

src/PlaybackManager.vala

If we're already playing a file we don't need to do any of this setup
Fixes a bug where track title was reset when adding new files

PlaybackManager: null check current_file when adding to queue

---

io.elementary.music.yml

* The 0.1.0 SDK doesn't exist
* zeitgeist is needed to build

flatpak: update SDK and add zeitgeist

---

src/PlaybackManager.vala

It appears that if the audio file doesn't have a title tag then Music uses the ugly file URI by default. This PR uses the prettier file basename if available otherwise falls back to the URI anyway.
See the track title on both panes - playlist on the left and above the progress bar on the right.
Before:
After:

Use file basename instead of uri for the default audio object title.

---

src/Application.vala
src/MainWindow.vala

Fixes #718 #721 
We've received a few duplicate issue reports about styles being broken on non-elementary OS systems. This hard codes styles to use the elementary ones. Since the icons and stylesheet are already included in the Flatpak platform, we can assume they exist

Application: hard code gtk styles

---

data/music.appdata.xml.in

Works with https://github.com/elementary/appcenter/pull/1883
Also add `light` and `dark` colors for future use in AppCenter

Metainfo: Use branding tag and screenshot caption

---

data/music.metainfo.xml.in
src/MainWindow.vala

Fixes #734 
This PR adds files contained within a dropped folder and within any subfolders to the queue.

Handle dropped folder

---

.github/workflows/ci.yml
.github/workflows/merge.yml
.github/workflows/release.yml
data/music.desktop.in
io.elementary.music.yml
src/Application.vala

These will be worked on a separate PR:
- ~~[ ] Add `audio/x-mpegurl` MIME type to .desktop file.~~
- ~~[ ] Support opening playlist files from code.~~
Fixes #709

Allow to open directories directly

---

data/meson.build
po/extra/meson.build
po/meson.build

Fix the following warning:
```
WARNING: Deprecated features used:
* 0.56.0: {'meson.source_root'}
```

meson: Fix build warning

---

src/PlaybackManager.vala
src/Widgets/TrackRow.vala

This adds the ability to remove single items from the queue, either by right clicking on the item or by using the "delete" keyboard shortcut on the selected item.
Fixes #787 
and implements another feature of #779 
Currently right clicking the song doesn't select it. This can make it hard to know which song will be affected by the action if you clicked somewhere in between two songs, because there is no visual cue to tell which song is selected. But I think that will be easier to fix that after we merged #796

Remove songs

---

meson.build
src/MainWindow.vala
src/Widgets/TrackRow.vala

MainWindow: replace ListBox with ListView

---

src/Views/NowPlayingView.vala

Correctly display artists name in NowPlayingView

---

data/music.gschema.xml
src/Application.vala
src/PlaybackManager.vala

The initial draft had no actual own save handler.
having a method for one but not the other felt awkward

Introduce save and restore methods

---

.github/workflows/ci.yml
.github/workflows/merge.yml
.github/workflows/release.yml
io.elementary.music.yml

Also replace deprecated `app-id` with `id` while I'm here

Flatpak: bump platform to 8.2

---

debian/control

Same with #826
- Fix missing libadwaita-1
- Explicit version limitation of granite-7

control: Update Build-Depends

---

data/music.gschema.xml
src/PlaybackManager.vala

Fixes #829
The default value of `previous-queue` is a string array with one element that has a blank URI. This results `last_session_uri.length` is not `0` but `1`, causing `last_session_files` has one File that has a blank URI.
https://github.com/elementary/music/blob/c2fc713067c0751bd5dc544f04fd5e7125dbf779/src/PlaybackManager.vala#L527-L541
causing the terminal warning here
https://github.com/elementary/music/blob/c2fc713067c0751bd5dc544f04fd5e7125dbf779/src/Application.vala#L141
and causing the toast popup here
https://github.com/elementary/music/blob/c2fc713067c0751bd5dc544f04fd5e7125dbf779/src/PlaybackManager.vala#L104-L130

gschema: Fix invalid default value for previous-queue
